In [110]:
import numpy as np
import open3d as o3d

print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("demo6.ply")
pcd_filted= o3d.geometry.PointCloud()

pcd = pcd.voxel_down_sample(voxel_size=0.04)
array_3d = np.asarray(pcd.points)


point_z = array_3d[:,2]
point_z = point_z > -4.0
array_3d = array_3d[point_z]
pcd_filted.points = o3d.utility.Vector3dVector(array_3d)

o3d.visualization.draw_geometries([pcd_filted])
print(np.array(pcd_filted.points).shape)
print(np.array(pcd_filted.points))

Load a ply point cloud, print it, and render it
(20370, 3)
[[ 2.68372    -2.33999    -3.718     ]
 [ 0.563307   -1.35755    -2.157     ]
 [ 0.295599   -1.28014    -2.034     ]
 ...
 [ 0.09007117  0.90380083 -3.586     ]
 [ 0.0721494   0.06022297 -2.77566667]
 [ 0.06836398  0.06260085 -2.7455    ]]


In [3]:
pcd_filted.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.3, max_nn=50))
o3d.visualization.draw_geometries([pcd_filted])
normals_vector = np.asarray(pcd_filted.normals)
print(normals_vector)
np.savetxt("normals_vector.txt", normals_vector)

[[-0.01337449  0.9995273   0.02768216]
 [-0.00918904  0.99961223  0.02628579]
 [-0.00839575  0.99963397  0.02571824]
 ...
 [ 0.97536092  0.07155272  0.20868944]
 [ 0.98982524  0.0775137   0.11932152]
 [ 0.07039861 -0.26984642  0.96032648]]


In [125]:
import open3d as o3d
pcd_normals = o3d.geometry.PointCloud()

pcd_normals.points = o3d.utility.Vector3dVector(pcd_filted.normals)
print(np.array(pcd.points))
print(np.array(pcd_normals.points))

coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5,origin=[0, 0, 0])
o3d.visualization.draw_geometries([pcd_filted,pcd_normals,coord_frame])
o3d.visualization.draw_geometries([pcd_normals, coord_frame])

[[-2.27421   1.87629  -2.971   ]
 [-2.26639   1.87629  -2.971   ]
 [-2.25857   1.87629  -2.971   ]
 ...
 [ 0.339943 -0.258671 -0.411   ]
 [ 0.341025 -0.258671 -0.411   ]
 [ 0.342107 -0.258671 -0.411   ]]
[[-0.01337449  0.9995273   0.02768216]
 [-0.00918904  0.99961223  0.02628579]
 [-0.00839575  0.99963397  0.02571824]
 ...
 [ 0.97536092  0.07155272  0.20868944]
 [ 0.98982524  0.0775137   0.11932152]
 [ 0.07039861 -0.26984642  0.96032648]]


In [ ]:
print(np.array(plane_pcd.points))
print("=========================")
print(np.array(pcd.points))

In [4]:
import open3d as o3d
import numpy as np
import time
# Đọc file ply chứa point cloud


t1 = time.time() 
pcd = o3d.io.read_point_cloud("example_official/demo4.ply")
pcd = pcd.voxel_down_sample(voxel_size=0.05)
array_3d = np.asarray(pcd.points)
point_z = array_3d[:,2]
point_z = point_z > -4.0
array_3d = array_3d[point_z]
pcd.points = o3d.utility.Vector3dVector(array_3d)
pcd_normals = o3d.geometry.PointCloud()
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.6, origin=[0,0,0])
t2 = time.time()


pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.3, max_nn=50))
pcd_normals.points = o3d.utility.Vector3dVector(pcd.normals)

t3 = time.time()
plane_model, inliers = pcd_normals.segment_plane(distance_threshold=0.005, #0.01,3,1000
                                         ransac_n=3,
                                         num_iterations=1000)
t4 = time.time()

plane_normal = pcd_normals.select_by_index(inliers)

pcd_show_plane = pcd.select_by_index(inliers)



pcd_normals.paint_uniform_color([1, 0, 0]) #red
plane_normal.paint_uniform_color([0, 0, 1]) #blue
pcd_show_plane.paint_uniform_color([1,1,0]) #yellow
o3d.visualization.draw_geometries([ frame,pcd_normals,plane_normal,pcd_show_plane])
print(np.array(pcd_normals.points).shape)
print(np.array(pcd.points).shape)
print(t4-t3)


(10179, 3)
(10179, 3)
0.010868310928344727


In [59]:
print(np.array(pcd.points).shape)
print(np.array(pcd_normals.points).shape)
print(np.array(pcd_show_plane.points).shape)
print(np.array(plane_normal.points).shape)


(10945, 3)
(10945, 3)
(1738, 3)
(1738, 3)


In [124]:
point_innormal = np.array(plane_normal.points)
print(point_innormal)
# print(point_innormal[0,:])
index_normal = np.where(abs(point_innormal[:,0]) < 0.4)
print(len(index_normal[0]))

[[ 0.99965349  0.02286976  0.01303353]
 [ 0.9992739   0.00318371  0.03796765]
 [ 0.99978054 -0.01953029 -0.00757886]
 ...
 [ 0.99997006 -0.00703792 -0.00321523]
 [ 0.99999215 -0.00357891 -0.00170037]
 [ 0.99975202 -0.01445197 -0.01694205]]
0
